class Intent:
    CHAT = "CHAT"
    OPEN_APPLICATION = "OPEN_APPLICATION"
    WEB_AUTOMATION = "WEB_AUTOMATION"
    DESKTOP_AUTOMATION = "DESKTOP_AUTOMATION"
    MEMORY_QUERY = "MEMORY_QUERY"
    STORE_MEMORY = "STORE_MEMORY"
    UNKNOWN = "UNKNOWN"